### ISSUE TITLE
Displaying status while viewing users in the admin view

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1005]
**AS AN** *Administrator*
**I WANT** *to see in Users module list, who is active and who is not*
**SO THAT** *I can easyle see who is currently working*

### Acceptance Criteria

- [ ] In user module list, there is added status column with green, yellow and red dots, indicating User statuses "Staatus":

https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=142-7595&node-type=frame&t=K5LZosFxpnKgapDX-0

**Comment by ffrose** [comment]
Works as intended.
