### ISSUE TITLE
[BUG] Emergency announcement start date

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1012]
**Bug description:** 
When adding an Emergency announcement (Administration - Chatbot - Emergency Announcements), the display period start date cannot be modified. Regardless of the date selected from the calendar, the start date field always defaults to its initial value. 

**Expected behavior:**
The start date field should allow modification, reflecting the selected date from the calendar. Additionally, the start date could default to the current date (today) for convenience.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/74b82235-da19-470b-9fbb-14795706bbf6)

**Additional information:**

This issue only affects the start date; the end date works as intended.

**Comment by ExiRain** [comment]
Should work now.

[Pull request](https://github.com/buerokratt/Buerokratt-Chatbot/pull/1023).

**Comment by ffrose** [comment]
As of right now, when Emergency announcement is turned off, it still provides a date from past.
![Image](https://github.com/user-attachments/assets/c1af2624-a0c1-478a-be28-71d081b9f424)
