### ISSUE TITLE
[BUG] CSA user rights fix

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#1015]
**Bug description:**
CSA has rights to see Training Module

**Expected behavior:**
When user has "Nõustaja" role, they should only see Chat Module and "Seire" Monitoring.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/593e5b2b-d3ea-4c76-b528-57d4e8187ff7)

**Comment by 1AhmedYasser** [comment]
English reference: https://github.com/buerokratt/Buerokratt-Chatbot/issues/547#issuecomment-2114768944
