### ISSUE TITLE
Unanswered conversations limit of 100 conversations in Prod

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1018]
**AS A** *Product manager*
**I WANT** *the forwarding system in PROD to work without issues related to unanswered conversations and the display limit of 100 conversations*
**SO THAT** *unanswered conversations can be properly managed and directed, and new chats can come through without issues caused by the limit.*

### Acceptance Criteria

- [ ]  Implement a temporary solution by increasing the display limit of unanswered conversations to 1000

**Comment by ffrose** [comment]
Limit is now over 100. As intended.
