### ISSUE TITLE
[BUG] Manually changing companies working time

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1021]
**Bug description:**

Modifying or deleting the time in Administration - Chatbot - Companies working time for the companies working hours via manual adding time is not functioning smoothly (for example, when user wants to add 35 minutes, then clock window adds only 3 and then shorts down, with results only with 03 min) . Users experience difficulties making quick adjustments to the time fields via the keyboard.

**Expected behavior:**

Users should be able to easily modify or delete working hours by directly typing in the time fields manually, ensuring a seamless and user-friendly experience.

**Sreenshot:**
![Image](https://github.com/user-attachments/assets/cb42e53b-4ee4-42f8-b3f1-3ca29d1d23d5)

**Additional information:**

This issue affects the efficiency of updating working time, especially when users prefer using the manual option instead of choosing preset times in dropdown list. For example it is working smootly in deleting chats module.

**Comment by IgorKrupenja** [comment]
Related PR:

- https://github.com/buerokratt/Buerokratt-Chatbot/pull/1035

**Comment by ffrose** [comment]
Works as intended.
