### ISSUE TITLE
Chat module conversation view

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#1029]
**AS A** *CSA*
**I WANT** *to see in conversations that Bürokratt/CSA messages are on the left side and End-User messages on the right side*
**SO THAT** *I can make a difference between Bürokratt/CSA and End-User more easily*

### Acceptance Criteria

- [x] CSA and Bürokratt answers on left side and End User text on right side (similar to widget.)
- [x] Same logic implemented in every view, 
"Vastamata" chat/unanswered / "Aktiivsed" chat/active / "Ootel" chat/pending

**Comment by ExiRain** [comment]
Should work good now:
![image](https://github.com/user-attachments/assets/41001048-113f-44b1-b7c5-2100278056ed)

Related [PR](https://github.com/buerokratt/Buerokratt-Chatbot/compare/dev...ExiRain:feature/1029-Conversations-view?expand=1).
