### ISSUE TITLE
[BUG] Organization working hours notice to End User with linked website

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1041]
**Bug description:**

When organization has added notice with website link, it is not clickable for End User

**Expected behavior:**

End User can click to website link

**Screenshots:**
End User view with notice and web link:
![Image](https://github.com/user-attachments/assets/a59cbb1f-0be9-4729-868d-a6bf391bd7de)

Outside working hours notice:
![Image](https://github.com/user-attachments/assets/8f75d9b1-c0af-421f-9f21-f8cfeed515e4)

**Additional information:**

**Comment by ffrose** [comment]
Works as intended.
