### ISSUE TITLE
Deploy Ruuter and its DSLs separately

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#155]
AS AN Architect
I WANT Ruuter and its DSLs to be deployed regardless of each other
SO THAT when updating DSLs, Ruuter base image should not be updated and vice versa

### Acceptance Criteria

- [ ] For Ruuter v1, an [existing image from Docker Hub](https://hub.docker.com/layers/riaee/byk-chatbot-public-ruuter/05/images/sha256-b3b7870e7317fcea4cd03c135c44fd5cc565ec76076bb74169acd5c283701187?context=explore) is used
- [ ] Ruuter v2 is built based on [Ruuter v2's source code](https://github.com/buerokratt/Ruuter)
- [ ] DSLs are deployed by using Docker volumes
- [ ] `docker-compose up` in case of deploying a new Ruuter Docker image
- [ ] `docker restart` in case only DSLs change

Appropriate Ruuter DSL's (depending on Ruuter's version) are applied by applying correct volumes as a source
- [ ] [Private Ruuter v1 DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.Ruuter-v1.private) are applied
- [ ] [Public Ruuter v1 DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.Ruuter-v1.public) are applied
- [ ] [Private Ruuter v2 DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.Ruuter.private) are applied
- [ ] [Public Ruuter v2 DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.Ruuter.public) are applied

**Comment by varmoh** [comment]
Updated Ruuter v1
V1 DSL's  (both public and private) are added using volume's as shown below:
`- ./DSL.Ruuter-v1.private:/usr/local/tomcat/configurations
`
`- ./DSL.Ruuter-v1.public:/usr/local/tomcat/configurations
`

**Comment by turnerrainer** [comment]
Close as covered by https://github.com/buerokratt/NoOps/issues/13
