### ISSUE TITLE
Chat widget available in test environment

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#170]
AS A Product owner
I WANT to have Chat Widget available in the test environment
SO THAT I could test new developments in the test environment

### Acceptance Criteria

- [ ] Use https://github.com/buerokratt/Chat-Widget as a source
- [ ] Chat widget is available via http://test.buerokratt.ee:3000
- [ ] Communication via Chat Widget and Backoffice is up and running

**Comment by turnerrainer** [comment]
Marking as blocked at the moment as http://test.buerokratt.ee:8080/custom-jwt-userinfo should respond with

```json
{"data":{"custom_jwt_userinfo":null},"error":null}
```

but is currently responding with

```json
{"response":{"headers":{},"body":{"sub":"","firstName":"MARY ÄNN","idCode":"EE60001019906","displayName":"MARY ÄNN","iss":"[test.buerokratt.ee](http://test.buerokratt.ee/)","exp":1670250948,"login":"EE60001019906","iat":1670243748,"jti":"e14a5084-3b30-4a55-8720-c2ee22f43c2c","authorities":["ROLE_ADMINISTRATOR"]},"statusCodeValue":200,"statusCode":"OK"}}
```

Will fix this later.

**Comment by turnerrainer** [comment]
Mock `custom-jwt-userinfo.yml` of Ruuter v2 should be as shown below:

`/DSL/GET/custom-jwt-userinfo.yml`

```json
return_value:
  wrapper: false
  return: "{\"data\":{\"custom_jwt_userinfo\":null},\"error\":null}"
```

**Comment by turnerrainer** [comment]
1. Solved by @varmoh by re-routing traffick using Nginx;
2. Bürokratt Test was deployed with MVP - widget working fine.
