### ISSUE TITLE
Bürokratt link problem solved and in PROD

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#174]
AS AN End User
I WANT to be able to open website when I click on the link
SO THAT I could get the info on that website

### Acceptance Criteria

- [x] All link displayed in Bürokratt are working

**Comment by KlviG** [comment]
Fix is done and tested in DEV env.
TO DO. Make fix in PROD after 15.00, so that customers are not disturbed.
