### ISSUE TITLE
Chatbot GUI issue

### ISSUE THREAD

**Issue by varmoh** [buerokratt/Buerokratt-Chatbot#244]
After building the new GUI image from the latest commit, my dev-tools show me an error right after the login (screenshot below).

![MicrosoftTeams-image (1)](https://github.com/buerokratt/Buerokratt-Chatbot/assets/101868197/61c52631-0672-4870-920d-4b034aecf4fa)

**Comment by 1AhmedYasser** [comment]
@varmoh Please Close this issue as it has been resolved and merged

**Comment by varmoh** [comment]
Validated
