### ISSUE TITLE
End-user can chat with Bürokratt

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#250]
AS A End-User
I WANT TO be able to ask a question and have it answered by Bürokratt.
SO THAT Bürokratt does not redirect messages to customer support agent, however, chat is visible in customer support module.

**Acceptance Criteria**

- [x] When a trained intent is identified, Bürokratt answers based on how it has been trained
- [x] When an untrained intent is identified, Bürokratt communicates that to end-user
- [x] When chat is forwarded to a CSA, previous conversation with Bürokratt will be transfered to CSA.

**Comment by ffrose** [comment]
BUG - When forwarding chat to a CSA, all previous messages End-User has sent are missing from the customer support module.


![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/a108d9d4-719f-4a5f-b678-d268f961733c)



![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/07b9806c-fab6-4a8d-8aee-a73eb8f35c61)

**Comment by ffrose** [comment]
BUG - CSA can't see End-User messages in the backoffice.


![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/cea6e459-5335-4b18-a763-e1bf9dabebb4)

**Comment by 1AhmedYasser** [comment]
> BUG - When forwarding chat to a CSA, all previous messages End-User has sent are missing from the customer support module.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/250019467-a108d9d4-719f-4a5f-b678-d268f961733c.png)
> 
> ![Image](https://user-images.githubusercontent.com/119657383/250019489-07b9806c-fab6-4a8d-8aee-a73eb8f35c61.png)

@varmoh Not happening in local side, please check it from your side

**Comment by 1AhmedYasser** [comment]
> BUG - CSA can't see End-User messages in the backoffice.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/250874783-cea6e459-5335-4b18-a763-e1bf9dabebb4.png)

@varmoh Not happening in local side, please check it from your side

**Comment by 1AhmedYasser** [comment]
> BUG - End-User sent a message containing "é" character. It turns to 0xE9. It shouldn't.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/252906515-eea179ac-b11a-48e5-b794-b7fd90f5b436.png)
> 
> BUG - I want to send text as a CSA to End-User without the "/n" that symbolizes a line change in backoffice, as user should not see that.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/252910578-ce640d8a-3eeb-43c0-beac-1207e2d19a01.png)
> 
> ![Image](https://user-images.githubusercontent.com/119657383/252910624-147d9707-7358-4d15-9cbd-eb4052885755.png)

@ffrose Can't break line anymore in UI so the second bug won't happen again
As for the first bug, still investigating a solution for it

**Comment by janinakimtrohlev** [comment]
> BUG - CSA can't see End-User messages in the backoffice.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/250874783-cea6e459-5335-4b18-a763-e1bf9dabebb4.png)

Testing right now. If I reply to client the answer does not appear to end user.

**Comment by janinakimtrohlev** [comment]
BUG - When i open the conversation and wants to take it on my name ("Võta üle") after that it shows wite page. And to continue i should go back and search this conversation from my Active conversations.

**Comment by janinakimtrohlev** [comment]
> é

I t

> > BUG - End-User sent a message containing "é" character. It turns to 0xE9. It shouldn't.
> > ![Image](https://user-images.githubusercontent.com/119657383/252906515-eea179ac-b11a-48e5-b794-b7fd90f5b436.png)
> > BUG - I want to send text as a CSA to End-User without the "/n" that symbolizes a line change in backoffice, as user should not see that.
> > ![Image](https://user-images.githubusercontent.com/119657383/252910578-ce640d8a-3eeb-43c0-beac-1207e2d19a01.png)
> > ![Image](https://user-images.githubusercontent.com/119657383/252910624-147d9707-7358-4d15-9cbd-eb4052885755.png)
> 
> @ffrose Can't break line anymore in UI so the second bug won't happen again As for the first bug, still investigating a solution for it

I tried to push as end user š and okey, but yes for example if i push é it gives to back office 0xE9.

**Comment by MarkusVeltri** [comment]
Working as intended.

**Comment by ffrose** [comment]
BUG - In chat history, spaces and symbols are swapped with "%".
![image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/26aa8b55-c60d-40e6-8239-be5a06dee164)

**Comment by rasmusei** [comment]
@ffrose, please check this, if it was closed properly and AC-s are completed
