### ISSUE TITLE
Widget: initial request returns NULL objects:

### ISSUE THREAD

**Issue by TarmoKlaarRIA** [buerokratt/Buerokratt-Chatbot#273]
tested 22.08.2023, env: dev.buerokratt.ee

Following request reutrns null object with statuscode 300:
https://ruuter.dev.buerokratt.ee/pub2/get-widget-config
{
    "response": null
}
https://ruuter.dev.buerokratt.ee/pub2/get-emergency-notice
{
    "response": null
}
https://ruuter.dev.buerokratt.ee/pub1/custom-jwt-userinfo
{
    "data": {
        "custom_jwt_userinfo": null
    },
    "error": null
}

![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119430244/d6e787e0-829d-4242-8998-4d4db585bfba)

![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119430244/94402156-0b08-4469-ac9f-fd3263c849a9)

**Comment by 1AhmedYasser** [comment]
<img width="1199" alt="273" src="https://github.com/buerokratt/Buerokratt-Chatbot/assets/26207361/87461cd3-393e-4568-9d43-19a0d9b4b101">

Working on the local side as shown in the video, needs to be rechecked on the dev environment

As for the `custom_jwt_userinfo` returning null, its normal because in order for this endpoint to return the data the user should be logged in, but here is using the chat bot anonymously, so when the user logs in the clientCustomJwtCookie is filled and used in `custom_jwt_userinfo` endpoint

<img width="1209" alt="273-screenshot" src="https://github.com/buerokratt/Buerokratt-Chatbot/assets/26207361/733c096a-b413-4268-aa85-c88c4bce1b63">

**Comment by TarmoKlaarRIA** [comment]
https://dev.buerokratt.ee/ 
Loading widget configuration works once and then doesn't work again. This morning the configuration was loaded, and the appearance of the widget changed. At the moment the tests show http.300 again and the color remains blue.
And another question, why is the configuration loading 2 times?

![image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119430244/c37df94d-fcac-4aca-ac2b-8bdc5514c51f)

**Comment by rasmusei** [comment]
@turnerrainer, take a look at Ahmeds comment:
There are 2 things that could be added as a fix
 
1- Disable Caching on Module index.html by adding (Not Recommended)
 


<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='expires' content='0'>
<meta http-equiv='pragma' content='no-cache'>

 
2- Control Caching on API's in Java in case of ruuter via HTTP Headers (Recommended)
     a- https://stackoverflow.com/questions/51524633/reactjs-how-to-prevent-browser-from-caching-static-files
     b- https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers
   
In java:    

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
response.setHeader("Pragma", "no-cache"); // HTTP 1.0.
response.setHeader("Expires", "0"); // Proxies.

 
What do you think is more appropriate to use in our modules ?
 
Note: For example in chatbot when trying to set the cache control header to the api requests it stopped working, so i think Ruuter needs to account for this headers when needed

**Comment by rasmusei** [comment]
@turnerrainer still waiting your comment

**Comment by turnerrainer** [comment]
@rasmusei @1AhmedYasser 
We'll solve it via https://github.com/buerokratt/Ruuter/issues/213. Ruuter enhancement, not a Chatbot bug.

**Comment by turnerrainer** [comment]
Should be resolved by Ruuter v1 -> Ruuter v2 migration. Will be fully resolved by #213
