### ISSUE TITLE
PPA sõnumid ei ole nähtavad klientidele / CSA messages are not visible to the end-user

### ISSUE THREAD

**Issue by janinakimtrohlev** [buerokratt/Buerokratt-Chatbot#326]
PPA kurdab, et tagatoas on ilusasti näha, et bot või teenindaja vastab, kuid klient hiljem küsib uuesti, tundub, et talle vastust ikkagi pole kuvatud, 
PPA poolt tagasiside on siis ka selline: 
Esimesel kolmel korral, kui Bürokratilt midagi küsisin ei vastanud Bürokratt mulle veebilehel mitte midagi. Kasutasin sülearvutit ja Chrome brauserit, küsisin kolmel erineval päeval, erinevatel kellaaegadel, erinevaid küsimusi ja vestlusaknas vastust ei kuvatud. Ka jätkuküsimustele vastuseid ei tulnud. Neljandal korral küsides oli sarnane olukord, kus mina küsisin küsimuse, Bürokratt ei vastanud, ma kirjutasin veel „tere“ ja ikka vastus puudus. Selle peale otsustasin veebilehte värskendada ja vestlusaknasse tekkisid minu tekstide vahele Bürokrati vastused. Seega oli ta mulle juba enne vastanud aga minu ekraanil seda ei kuvatud. 

Google translate:
PPA complains that in the back room it is seen that a bot or an attendant is answering, but the customer later asks again, it seems that the answer still hasn't been shown to him.
The feedback from PPA is as follows:
The first three times I asked the Bureaucrat something, the Bureaucrat didn't answer me anything on the website. I used a laptop and a Chrome browser, I asked different questions on three different days, at different times, and the chat window didn't show an answer. There were no answers to follow-up questions either. The fourth time I asked, there was a similar situation where I asked a question, the Bureaucrat did not answer, I wrote "hello" again and there was still no answer. After that, I decided to refresh the website, and the answers of the Bureaucrat appeared between my texts in the chat window. So he had already answered me before, but it was not displayed on my screen.

**Comment by KlviG** [comment]
Hüpoteesi kohaselt võib olla probleem seotud helitevituse probleemiga.
Hetkel ootab arenduse fixi

**Comment by rasmusei** [comment]
@KlviG please check this task. If all working, then please write so and mode it to done.

**Comment by turnerrainer** [comment]
Blocked by https://github.com/buerokratt/Buerokratt-Chatbot/issues/358
