### ISSUE TITLE
Chats, finished with giving contacts, in the BYK back-office

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Buerokratt-Chatbot#374]
AS A CSA
I WANT TO have the chats that have been ended from end-user side with their contact information provided to be separated from other incoming chats
SO THAT I have a clear distinction for the chats that I need to respond to later through another channel

Task has relation to #1

### Acceptance Criteria

- [x] Separate page Pending (Ootel) created for these chats, located btw active and historic chats in the back-office menu. Follow the unanswered chats' page design https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2325-15012&mode=design&t=zykJcJ7gxOJciJXA-4
- [x] Page has two sections for chats - 1) new (uued) 2) in process (töös)
- [ ] Page has same buttons available as in Unanswered page
- [x] CSA can take over the chat from New section,, after that chat is moved to In Process section, under CSA name (similar to active chats)
- [x] Since chat is terminated from End-user side, reply functionality in the chat is disabled.
- [x] Third status beside existing Open and Closed is created for these chats - Idle. When chat is terminated from end-user side, it gets Idle status and is moved to the page (above).
- [x] When chat is terminated by CSA, it is moved to History page.

**Comment by rasmusei** [comment]
Blocked by menu and header part. @1AhmedYasser will you create a task for that?

**Comment by 1AhmedYasser** [comment]
> Blocked by menu and header part. @1AhmedYasser will you create a task for that?

Task: https://github.com/buerokratt/Buerokratt-Chatbot/issues/432

**Comment by 1AhmedYasser** [comment]
PR for #432 is now merged, this is not blocked anymore

**Comment by janinakimtrohlev** [comment]
BUG - Right now as CSA I can´t open chat in Separate page Pending (Ootel). So I can´t test.  It doesn´t open old chats and also new chats in Separate page Pending (Ootel).

**Comment by janinakimtrohlev** [comment]
Bug - Right now if I open chat with contact information, it gives button "Võtta see" but should be button "Võtta üle".

**Comment by janinakimtrohlev** [comment]
BUG - when I as CSA open OOTEL chats I see chats which is in work ( Töös) it is okey, but if I open some chat on Töös I can immediately put statuses 1)Kasutajani ei õnnetunud jõuda 2) Kasutajaga ühendust võetud.

First it should ask me to take this chat on my name, so first it shoul be button "Võta üle" and after that I only should choose options 1)Kasutajani ei õnnetunud jõuda 2) Kasutajaga ühendust võetud.

**Comment by 1AhmedYasser** [comment]
Blocked waiting for #452

**Comment by varmoh** [comment]
Deployed, moving to AT

**Comment by janinakimtrohlev** [comment]
Tested and done.
