### ISSUE TITLE
Ruuter V2 Migration Bugs

### ISSUE THREAD

**Issue by 1AhmedYasser** [buerokratt/Buerokratt-Chatbot#405]
This Issue will contain any found bugs on the dev environment on Ruuter V2 New Migration

When reporting bugs, please do the following:

1. Report each bug in a separate comment
2. Provide as much information as possible to help reproduce it on my side
3. Provide a screen shot or a video if possible

**Comment by ValterAro** [comment]
Short summary: when in the chat widget page (https://dev.buerokratt.ee/). There is this weird behaviour with the thumbs up and thumbs down button, that when you press either one as a customer then it replicates the message and it shows this as a new message from the csa (sometimes from the customer) on the customer chat widget side.
Expected result: I guess it should just light up the option you chose.
Real result: It shows a new message from the csa
How to replicate: Open the (https://dev.buerokratt.ee/) and start a conversation, then say "suuna" and also accept the conversation on the csa side and say something.
Then as a customer press either thumbs up or down.
Pic:


![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122787093/6dddd984-a518-44f1-a214-57c8477dd992)



![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122787093/51bd84f5-c758-4bfe-a2a9-6664b5269cc3)

**Comment by ValterAro** [comment]
Short summary: After the csa ends the chat the customer is not notified unless he sends a new message in the chat widget.
Expected result: After the csa ends the chat then the customer should be immediately be prompted with the feedback for the conversation.
Real result: the chat widget stays the same.
How to reproduce: start a chat as a customer and say "suuna" to access the chat as a csa. Then as a csa take over the chat and end it. You then see that the customer does not see that the chat has been ended even after 5 minutes.
Pic:


![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122787093/4b4ae302-3fc5-4d1c-aed3-8d8ad5362808)



![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122787093/d21d5e30-bebe-45eb-9808-4a0f8de340b5)

**Comment by turnerrainer** [comment]
Closed as migration is finished in `dev`.
