### ISSUE TITLE
Define rules to define who / what / how responds to chat requests

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#44]
AS A Business Owner
I WANT the same rules to be applied on how to respond to End User requests
SO THAT I could be sure that the same process applies to all requests

### Acceptance Criteria

- [ ] By default, all unanswered requests are first sent to an automated chatbot
- [ ] Requests are forwarded to CSAs only during their working hours and when at least 1 CSA is active
- [ ] Automated chatbot responds regardless of CSA's working hours
- [ ] Fallback in case of an automated chatbot is unable to answer is to ask if the End User wants to leave their contact so that CSA could contact them later in person
- [ ] Fallback in case there are more than a predefined number of End Users waiting in the live queue is to ask if the End User wants to leave their contact so that CSA could contact them later in person
- [ ] Fallback in case an estimated waiting time exceeds the predefined value (in seconds) of End Users waiting is to ask if the End User wants to leave their contact so that CSA could contact them later in person

**Comment by rasmusei** [comment]
task is done on task #1
