### ISSUE TITLE
Queue number is displayed when at least one CSA is available (green) or idle (yellow)

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Buerokratt-Chatbot#445]
AS an End-User
I WANT TO have the queue number displayed when directed to back-office
SO THAT I can decide whether stay waiting or provide my contact for later reply from CSA

related to #48 
Figma link https://www.figma.com/file/9Lpy6pdvYaq2M6PxUO6ym4/B%C3%BCrokratt-(Copy)?type=design&node-id=696-83001&mode=design&t=58GL5MhoUAK0uyAu-4

### Acceptance Criteria
- [ ] conversations directed to the CSA obtain a queue number
- [ ] queue number must be dynamic - if conversation with smaller queue number is taken over by CSA, all conversations with larger queue number will be changed to one number smaller (as a side note - CSA can take over any conversation, not only the first in line)
- [ ] queue number is displayed to the end-user after conversation is directed to CSA and when at least one CSA is available (green) or idle (yellow). When not available, contact information is asked according to #1 
- [ ] End-user sees the change in queue number immediately
- [ ] Text displayed to End-User: "All customer service representatives are currently busy. You are xx in the queue." - in Estonian "Kõik klienditeenindajad on hetkel hõivatud. Olete järjekorras xx. kohal."
- [ ] When the conversation is taken over by a CSA, the queue message will disappear.

**Comment by 1AhmedYasser** [comment]
@varmo Needs Widget and notification layer rebuild on deploy

**Comment by janinakimtrohlev** [comment]
BUG As an End User I don´t see any queue number. Also it doesn´t show question to forward to CSA or to leave contact information.

**Comment by rasmusei** [comment]
BUG - Queue number is still not displayed. Note to @baha-a, queue number must be shown from the 1st end user and even if it's the only end user.

**Comment by baha-a** [comment]
Related PRs:
- https://github.com/buerokratt/Chat-Widget/pull/100
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/471
