### ISSUE TITLE
Notification of the authentication result is displayed

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#46]
AS A CSA
I WANT TO see if the End Users authentication has been successful or unsuccessful
SO THAT I have an instant understanding of when authentication is done

### Acceptance Criteria

- [x] When authentication is successful then the notification will be displayed on the chat's CSA view with appropriate text
- [ ] When authentication is not successful then the notification will be displayed on the chat's CSA view with appropriate text

**GUI**

- [ ] Notification is part of a regular message flow but is marked accordingly
- [ ] Notification is shown in CSA's chat window
- [ ] Based on [Figma design](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=142%3A4282&starting-point-node-id=1%3A2&scaling=contain)
![image](https://user-images.githubusercontent.com/90505798/211027381-090fd94a-74c1-457f-a14d-e73a695e9d8b.png)

**DSL**

- [ ] Add an additional step to an existing DSL (End User authenticates via TARA) to make a request to `post-message`
- [ ] `post-message` adds an entry to `messages` table with appropriate data and marking it as a system notice instead of a regular message

**Comment by rasmusei** [comment]
Prototype is covered in #39

**Comment by helemand** [comment]
`cs-get-messages-by-chat-id` includes the following entry:
```
{
    "cs_get_messages_by_chat_id": [
        {
            "id": "7d9cc156-6934-473c-92d8-81462e212765",
            "chatId": "3b71c597-cbb7-4f6e-ba99-a77acaefbe11",
            "content": "",
            "event": "authentication_successful",
            "authorId": "",
            "authorTimestamp": "2023-02-06T08:17:33.790+00:00",
            "authorFirstName": "",
            "authorLastName": "",
            "authorRole": "backoffice-user"
            "forwardedByUser": "",
            "forwardedFromCsa": "",
            "forwardedToCsa": "",
            "rating": "",
            "created": "2023-02-06T08:17:33.791+00:00",
            "updated": "2023-02-06T08:17:33.802+00:00"
        }
    ]
}
```

**Comment by 1AhmedYasser** [comment]
> BUG - When CSA asks for authentication(Küsi autentimist), End-User doesn't get any messages.
> 
> ![Image](https://user-images.githubusercontent.com/119657383/257815279-4240e3dd-0beb-4b8a-bbae-1d2b7c3a4bd5.png)
> 
> ![Image](https://user-images.githubusercontent.com/119657383/257815660-3e4230a1-95c1-450e-aa37-41085f495100.png)

@turnerrainer @varmoh Working on local side, please recheck it on the play environment side

**Comment by janinakimtrohlev** [comment]
@varmoh on our side it tells that is is asking. But for end user authentication request is not coming.

**Comment by rasmusei** [comment]
Needs test TARA for testing

**Comment by turnerrainer** [comment]
Blocked due to https://github.com/buerokratt/Buerokratt-Chatbot/issues/111

**Comment by janinakimtrohlev** [comment]
BUG - When as End User tries to authenticate himself it takes to Tara options, but then it goes to widget back and there is no conversation. So it close conversation.
Should be if I as End User authenticate himself it should continue to the same chat and tells that you are authenticated and for CSA will go information about authentication.

**Comment by janinakimtrohlev** [comment]
Right now I can´t test. Because asking and authentication from client is not working right now.

**Comment by janinakimtrohlev** [comment]
Tested.
BUG- AS CSA I initiate an authentication. As for end user it gives me choice to authenticate. But after authentication it goes back to chat and still give choice to authenticate. Also no information about that End User is authenticated doesn´t come to CSA. 
Should be when End user authenticate in chat will be wrote that end user authenticated. And after that information of authentication should see also a CSA.

**Comment by janinakimtrohlev** [comment]
BUG - I tested and as CSA I can initiate an authentication. But as End User I authenticate and it asks me again to authenticate. So the system don´t see that I did it already.

Should be as an End User I authenticate and it will show that I´m authenticated. Also this information about authentication should go to CSA.

**Comment by janinakimtrohlev** [comment]
BUG- tested and after client is authenticateed it doesn´t give an notification result.

**Comment by janinakimtrohlev** [comment]
Tested and Done
