### ISSUE TITLE
Ruuter DSL to launch services based on intents

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#477]
AS A Product Owner
I WANT Services to be launched based on detected intents if they exist
SO THAT End Clients could use (gov) e-services where via chat when applicable

### Acceptance Criteria

- [ ] Add an additional step to Ruuter DSL to validate from an approriate Postgres database if Rasa response has a matching Service
- [ ] Keep all other functionalities as they are right now

#### Scope

- [ ] [Ruuter DSL accepting End Client's requests](https://github.com/buerokratt/Buerokratt-Chatbot/blob/dev/DSL/Ruuter.public/DSL/POST/message-to-bot.yml)
- [ ] A database table called `service_triggers` linking intents and Services

#### Prerequisites

- [ ] buerokratt/Ruuter#271

#### Intended workflow nr. 1

- [ ] The End Client sends a message "Tere" _("Hello" in Estonian)_
- [ ] Ruuter sends the request AS IS to Rasa, which responds with "Kuidas saan abiks olla?"
- [ ] Ruuter does not detect `#` as the first character of Rasa's response, so passes the response AS IS to the End Client

#### Intended workflow nr. 2

- [ ] The End Client sends a message "Ilm Tallinnas" _("What's the weather like in Tallinn" in Estonian)_
- [ ] Ruuter sends the request AS IS to Rasa, which responds with `"#weather; Tallinn;"`
- [ ] Ruuter detects `#` as the first character of Rasa's response, so passes `weather` to Postgres to validate if there's a matching Services linked to it
- [ ] If a matching Service exists, it will be triggered by Ruuter as a standard REST call to an external endpoint
- [ ] The response received from the external endpoint is added to Bürokratt's Chat database

#### Intended workflow nr. 2

- [ ] The End Client sends a message "Ilm Tallinnas" _("What's the weather like in Tallinn" in Estonian)_
- [ ] Ruuter sends the request AS IS to Rasa, which responds with `"#weather; Tallinn;"`
- [ ] Ruuter detects `#` as the first character of Rasa's response, so passes `weather` to Postgres to validate if there's a matching Services linked to it
- [ ] If a matching Service does not exist, a response indicating that the Service is currently unavailable is sent as a predefined `i18s` key called `service_currently_unavailable`

**Comment by KlviG** [comment]
checkservice:
  switch:
    - condition: ${incoming.body.list[0] === "#weather"}
      next: weatherService
    - condition: ${incoming.body.list[0] == null}
      next: noService
  next: noService

weatherService:
  call: http.post
  args:
    url: https://ruuter.buerokratt.something.ee/get-things
    body:
     locationName: ${incoming.body.list[1]}
     chatId: ${incoming.body.chatId}
     authorId: ${incoming.body.authorId}
  result: weatherRequest
  next: end

noService:
  return: "${incoming.body.list[0]} , NO_SERVICE"
  status: 400
  next: end
