### ISSUE TITLE
Chatbot recognizes End User's language preference

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#5]
AS AN End User
I WANT Chatbot to automatically detect my preferred language and display chat widget in that language, 
SO THAT I can understand the content better

### Acceptance Criteria

- [ ] End User's preferred language is detected automatically and UI is changed into that language

**Comment by turnerrainer** [comment]
@rasmusei 
Should be done throughout all GUI elements via https://github.com/buerokratt/Buerokratt-Chatbot/issues/49

**Comment by rasmusei** [comment]
Won't do in MVP2, will be done in machine learning part
