### ISSUE TITLE
BUG - Unable to send attachments

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#576]
AS A CSA or End-User
I WANT TO be able to send attachments
SO THAT i can provide information through files.

When trying to send attachments as a CSA, it does nothing. When clicking "Send attachments" it gives me the option to choose the file yet when i select this it does not do anything.

![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/9d63356f-c1e0-4ea1-9619-8f8f3105e752)

When trying to send attachments as a End-User i am able to select for example a screenshot. It sends a text not an actual file. Acts the same for CSA. 

![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/119657383/3167f969-873e-4a3c-ab59-e9a55c464295)

**Comment by turnerrainer** [comment]
The functionality hasn't been fully developed. Close this issue and continue under it's parent issue.
