### ISSUE TITLE
Bot has to ask from end-user weather to forward the chat to back-office

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Buerokratt-Chatbot#664]
BUG description: in case bot cannot reply, it automatically forwards the chat to the back-office. In case no CSAs are available, contact information is asked and chat is closed automatically.

Should be: in case bot cannot reply, it must ask from end-user, if he/she wants the chat to be forwarded to the back-office. Chat will be forwarded only after positive answer is received from the end-user, otherwise the chat will remain open.

**Comment by jaX10bt** [comment]
Blocked

Unable to test because whenever the bot can not answer, the chat is sent to LLM

**Comment by turnerrainer** [comment]
https://github.com/buerokratt/Common-Services/issues/71
