### ISSUE TITLE
Make links that include symbol "-" hyperlinks in UI, instead of regular text.

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#73]
AS A Chat User
I WANT TO send and receive URLs as clickable links
SO THAT I wouldn't have to copy/paste them

### Problem statement

- Current Bürokratt chat uses [Linkify](https://linkify.js.org) to turn URLs into links
- If provided URL contains `-`, links are served as plain text

### Acceptance Criteria

- [ ] Re-produce the problem
- [ ] Apply fixes
- [ ] Provide a step-by-step guide to add updates to client servers
- [ ] Apply changes to client servers (internal)

**Comment by Kristjanmn** [comment]
Issue was Linkify not concidering links including '-' as valid links.
Issue can be resolved by changing a line 7 in `/src/components/chat-message/message-types/linkifier.tsx` from `const regex = /https:\/\/([a-zõäöüA-ZÕÄÖÜ0-9.]+[\\/]?)+$/;` to `const regex = /https:\/\/([a-zõäöüA-ZÕÄÖÜ0-9.-]+[\\/]?)+$/;`

**Comment by Kristjanmn** [comment]
Committed and pushed [bugfix](https://github.com/buerokratt/Chat-Widget/commit/6c0a0e44774ffae043c6085e580d6476eed712c2) to [Chat-Widget](https://github.com/buerokratt/Chat-Widget) repo.
