### ISSUE TITLE
[BUG] 'Küsi nõusolekut' button loading animation stalling

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#752]
AS A backoffice user
I WANT TO ask the client for permission and see the loading bar decrease smoothly within a predetermined time window
SO THAT I am unable to push the button until a reasonable time has passed

In /chat/active currently the loading bar does not decrease within a specified time

![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/132996313/6677878c-a208-42b1-91db-03f05a048353)

**Acceptance Criteria**

- [ ] After pressing the 'Küsi nõusolekut' button in /chat/active, the gray loading bar decreases smoothly within the specified time.

**Comment by ffrose** [comment]
Works as intended.
