### ISSUE TITLE
Remove 'ask for contact details' from widget when CSA is online

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#802]
AS AN end user
I WANT TO not have to leave my contact information when a CSA is available
SO THAT I can only leave contact information when a CSA is not available

Currently when a chat is forwarded to CSA, the chatbot asks for the clients contact information even if a customer support agent is available.

Clients position in the CSA queue should be removed.

**Acceptance Criteria**

- [ ] When a chat is forwarded to CSA and CSA is online, the chatbot won't ask for contact details.
- [ ] When a chat is forwarded to CSA and CSA is not online, the chatbot will ask for contact details.
- [ ] When a chat is forwarded to CSA, the widget will not show the current queue position.

Related to task: https://github.com/buerokratt/Buerokratt-Chatbot/issues/1

**Comment by yb-ng** [comment]
PR:
https://github.com/buerokratt/Chat-Widget/pull/299
