### ISSUE TITLE
Saving a rule when adding an intent

### ISSUE THREAD

**Issue by Kristjan259** [buerokratt/Buerokratt-Chatbot#804]
AS A Chatbot Trainer
I WANT TO that when I define an intent an answer is mapped to it
SO I WOULD know that when a specific intent is classified it would answer in the programmed matter

## Acceptance Criteria

- [ ] A view where the user can define the intent and answer 
- [ ] The answer has to show up on the answers page
- [ ] This rule has to show up under the rules tab

New Intent view according to Figma: https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=0-1&t=bt7bejhBT1TPUvHx-0

**Comment by turnerrainer** [comment]
Blocked, @joonasroosalung to specify.

**Comment by joonasroosalung** [comment]
Unable to run Training-Module repo locally, @buerokratt-ria/header unable to resolve howler.js dependency

`Uncaught SyntaxError: The requested module 'http://localhost:3001/training/node_modules/howler/dist/howler.js?v=7b64b624' doesn't provide an export named: 'Howl'` in `@buerokratt-ria/header/src/hooks/useAudio.tsx`

Similar issue in Analytics-Module when trying to run locally with Dockerfile.dev

@varmoh is contacting original developers

**Comment by joonasroosalung** [comment]
PR https://github.com/buerokratt/Training-Module/pull/626

**Comment by Kristjan259** [comment]
The new page is not visible in the test environment.



![Image](https://github.com/user-attachments/assets/1ff4c1a3-697c-4db5-8d0d-3a869805e15f)

**Comment by Kristjan259** [comment]
Seems to be working as in intended in the test environment.
