### ISSUE TITLE
[BUG] On-Hold chat buttons do not fit the screen.

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#817]
[BUG]

When taking over On-Hold chats it provides me with two buttons. "Kasutajaga ei õnnestunud ühendust saada" and "Kasutajaga ühendust võetud" These buttons do not fit.
![image](https://github.com/user-attachments/assets/8373ef6a-4d57-4a3c-8009-f2537483bd74)

**Comment by yb-ng** [comment]
PR:
https://github.com/buerokratt/Buerokratt-Chatbot/pull/841
