### ISSUE TITLE
Add functionalities to Training Module rules

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#829]
AS A Chatbot Trainer
I WANT TO utilize all available Rasa functionalities when creating rules
SO THAT rules won't be broken after modifying them in Training Module GUI

Currently there is functionality to check the value of a slot in the condition of a rule, but there should also be functionality to check whether a specific slot has been set.

Example of a rule with functionality to check whether a specific slot has been set:
![Image](https://github.com/user-attachments/assets/35c484b4-4fe1-4d3e-917e-5d92e162e178)

**Comment by jaX10bt** [comment]
It is possible to check whether a slot has been set, but the rule syntax is broken by double quotes:
GUI:
![image](https://github.com/user-attachments/assets/a05bda8e-3539-4277-833f-dff8fb71b250)
rules.yml:
![image](https://github.com/user-attachments/assets/dd6f6aa5-8322-47b9-a87b-1ff2bbd6abb8)

How it should be:
```
- slot_was_set:
          rk_hääletus: null
```
Slot value should be without double quotes

It should also be possible to check multiple slots in a single slot_was_set check as it is with entities in intents:
![image](https://github.com/user-attachments/assets/048a8cc3-33b4-40d0-9e11-247bbb81a77b)

**Comment by jaX10bt** [comment]
The double quotes need to be checked with @varmoh or @KlviG on the dev environment.
Also need to discuss slot block separation with @rasmusei and @turnerrainer 
Note: logic is currently working but improvement ideas to be discussed.

Blocked until further discussion

**Comment by jaX10bt** [comment]
Blocker resolved. To deploy.

**Comment by ffrose** [comment]
Works as intended, when filling slots there are no more double quotes.
