### ISSUE TITLE
[BUG] On Hold chat shows bot response after client has left contact details

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#830]
When an end user tries to contact CSA outside of working hours and leaves their contact details, the contact details are forwarded to backoffice with the end users request. However when viewing the chat in the backoffice, it is evident that the bot is trying to respond to the end users last request.

How it is:
![Image](https://github.com/user-attachments/assets/164eb87a-b980-40a2-a7b3-374eaa3a2a62)

How it should be:
After the end user leaves their contact details and request, the chat should end and the bot should not try to respond.

**Comment by SanderSepp** [comment]
https://github.com/buerokratt/Chat-Widget/pull/301

**Comment by ffrose** [comment]
Works as intended.
