### ISSUE TITLE
Refactor message-to-bot internal endpoint

### ISSUE THREAD

**Issue by RayDNoper** [buerokratt/Buerokratt-Chatbot#865]
Currently message-to-bot (Buerokratt-Chatbot/DSL/Ruuter.public/DSL/POST/internal/message-to-bot.yml) is a massive mostly-hardcoded DSL that handles all directions user interaction with bot and services can go.

#### Acceptance Criteria

> [!NOTE]
> The scope of this task is to become market-ready ASAP
> Actual refactoring of this whole functionality will be based on https://github.com/buerokratt/Training-Module/issues/393 and via another task (TBA)

- [ ] Use current hard-coded solution to become market-ready ASAP
- [ ] Make sure that the End Client doesn't see `SKIPRASA` or other similar messages that they don't need to see
- [ ] Validate all services by accessing them via Chat Widget
- [ ] ~Allow button payloads to directly access endpoints - currently payload passes through chat and is visible to user~
- [ ] ~Split DSL to manageable templates~
- [ ] ~Refactor hard-coded functionality (requests to services)~

#### Scope

- [ ] https://github.com/orgs/buerokratt/projects/47/views/41

**Comment by jaX10bt** [comment]
initiate-service removed in #868, removing all common services starting with #.

**Comment by turnerrainer** [comment]
Won't do. Will do it properly, starting with https://github.com/buerokratt/Buerokratt-Chatbot/issues/882.
