### ISSUE TITLE
Format the output of external LLM to be more human-readable

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#885]
AS AN End Client
I WANT the output of external LLM to be formatted
SO THAT it would be more human-readable

### Acceptance Criteria

- [x] Applies on all responses of an external LLM
- [x] Auto-detect and format headers
- [x] Apply newlines
- [x] Auto-detect and format **bold** text
- [x] Auto-detect and format _italic_ text
- [x] Auto-detect and format **_italic bold_** text in _**both ways**_
- [x] Auto-detect and format headers
- [x] Apply changes in Chat Widget
- [x] Apply changes in Backoffice

**Comment by 1AhmedYasser** [comment]
Point to note:

* There are 6 types of headers

1) #
2) ##
3) ###
4) ####
5) #####
6) ######

* Headers must start with a hashtag followed by space and its only ended by a new line
