### ISSUE TITLE
[BUG] Chat History pagination problem

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#896]
[BUG]

How it is:
Problem occurs in /chat/history, in /training/history/history and /chat/users, pagination numbers do not fit in the card. (Screenshot and recording provided below)
![Image](https://github.com/user-attachments/assets/69c338e4-ac13-469a-9492-a5de6492e671)https://github.com/user-attachments/assets/a0f2067b-fc61-4a6e-ada1-2231ed08afc9

How it should be:

- [x] Clicking on a number moves the pages forward
- [x] Using the arrows you are able to move forwards or backwards by one
- [x] First page and last page are stationary
- [x] It should show visually next 2(two) pages and last 2(two) pages as you move forwards or backwards, so as an example when i am on the 6th page i can see: <-1 ... 4 5 6 7 8... 19 ->

3 examples:
Beginning
- <- 1 2 3 ... 19 ->
Middle
- <-1 ... 8 9 10 11 12 ... 19 ->
End
- <-1 ... 17 18 19 ->

**Comment by jaX10bt** [comment]
Works as intended
