### ISSUE TITLE
Working time problem

### ISSUE THREAD

**Issue by ffrose** [buerokratt/Buerokratt-Chatbot#897]
[BUG]

How it is:
In chat/working-time, i am able to set the end time before the starting time. 
![Image](https://github.com/user-attachments/assets/637c7289-75e5-485f-ae7f-9c39bb7a9ae4)

How it should be:
When starting time would be for example 08:00 then upon opening the end time drop down menu, it shouldnt show times that are before 08:00

**Comment by ExiRain** [comment]
[Pull Request with changes](https://github.com/buerokratt/Buerokratt-Chatbot/pull/907)

**Comment by jaX10bt** [comment]
Works as intended
