### ISSUE TITLE
Changes in working hours

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#914]
AS AN Administrator
I WANT TO be able to set organization's working time to 24/7 and missing CSA notification
SO THAT chatbot works optional 24/7 . Will send notification, if there are no CSA-s currently online and asks End Users contact information if End User wants Administrator to contact them.

### Acceptance Criteria

- [x] Administrator can choose  organization's working time  24/7  ("Asutuse tööaeg on 24/7") is Yes/No  ("Jah/Ei")
- [x] Administrator can choose  organization's working time  within certain hours - AS IS
- [x] Administrator can choose, when there is currently no CSA online, that Bürokratt displays only editable notification ("Saada kliendile teavitus eemalolekust") Yes/No ("Jah/Ei"). And End User will receive notification, that there is no CSA currently available, please try again later ("Hetkel ei ole ühtegi vaba klienditeenindajat, palun proovige mõne aja pärast uuesti")
- [x] Administrator can choose, when there is currently no CSA online, that Bürokratt displays notification + contact information field ("Saada kliendile teavitus eemalolekust koos kontakti päringuga") Yes/No ("Jah/Ei"). And End User has notification, that there is no CSA currently available and will display contact form with editable header text with contact field ("Hetkel ei ole ühtegi vaba klienditeenindajat, palun täitke kontaktivorm ja võtame Teiega ühendust!")
- [x] Administrator can choose only one: AC 3 or AC 4, not both

### New AC-s

- [x] CSA missing message box name should be "Klienditeenindaja eemaloleku teavitus", currently it is "CSA pole saadaval teade"
- [x] Organization is out of working hours notice box name in "Väljaspool tööaega", and box text is editable
- [x] Administrator can choose, when organization is out of working hours, public holiday etc, that Bürokratt displays only editable notification ("Saada kliendile teavitus ettevõtte välisest tööajast") Yes/No ("Jah/Ei"). And End User will receive editable notification, that organization is out of working hours, please try again later ("Hetkel on tööväline aeg, palun proovige mõne aja pärast uuesti")
- [x] Administrator can choose, when organization is out of working hours, public holiday etc, that Bürokratt displays notification + contact information field ("Saada kliendile teavitus töövälisest ajast koos kontakti päringuga") Yes/No ("Jah/Ei"). And End User has notification, that organization is out of working hours and will display contact form with editable header text with contact field ("Hetkel ei ole ettevõtte tööaeg, palun täitke kontaktivorm ja võtame Teiega ühendust!")
- [x] Administrator can choose only one: AC 7 or AC 8, not both

### New AC

- [x] Additionally all the rules when CSA is offline should apply also when CSA is in idle status (yellow)

**Comment by ffrose** [comment]
Tested in TEST environment, this stays in Testing until we can test this in PROD environment.

**Comment by ffrose** [comment]
Working as intended.
