### ISSUE TITLE
Chat history listing view

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#940]
**AS AN** *Administrator*
**I WANT** *to open and view chats from a list while keeping the ability to browse and open other chats on the left side*
**SO THAT** *I can quickly switch between chats without losing the list view*

### Acceptance Criteria

- [x]  In the chat list view, each chat has a view "Vaata" button that allows the admin to open a selected chat
- [x] When a chat is opened, the chat list remains visible on the left side of the screen, allowing the admin to browse and select other chats
- [x] The selected chat opens in a main viewing area on the right side of the screen, separate from the list view
- [x]  Clicking view "Vaata" on another chat, updates the main viewing area with the newly selected chat

**Comment by ExiRain** [comment]
Currently allows to select any conversation and would update dialog window,view button sticks to the left of chat so no matter where you scroll in horizontal the VIEW button always there for use.
![image](https://github.com/user-attachments/assets/fe7dfb02-f25c-48ac-a35b-cfc62d476cbb)


Pull [Request](https://github.com/buerokratt/Buerokratt-Chatbot/pull/1039).

**Comment by ffrose** [comment]
Works as intended.
