### ISSUE TITLE
[BUG] Administrator receives error as turning off/on displaying CSAs title

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#944]
**Bug description:** In Chatbot settings administrator can't turn off CSA title, as it gives error that is shown in screenshot 1. It seems to be saving selected off option, but gives error message. As a result, it seems that in chatbot Title is removed when CSA answers to End User (screenshot 2). When turning back on Title function, it seems not to appear to End User (screenshot 3).

**Expected behavior:** When administrator turns off CSA title and presses save "Salvesta" it changes CSA title off and gives notification updated successfully "Värskendamine õnnestus".

**Screenshots:**
![Image](https://github.com/user-attachments/assets/9477b4ef-4805-405b-b9ee-548a961bcb1b)
![Image](https://github.com/user-attachments/assets/0f87552c-38d3-4b84-bf4b-5d244d3cc253)
![Image](https://github.com/user-attachments/assets/e1ba65ec-9b60-4c0c-aa80-4a98ac81b783)

**Additional information:**

**Comment by jaX10bt** [comment]
Seems to be working as intended
