### ISSUE TITLE
[BUG] Analytics module feedback to CSA not available

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#945]
**Bug description:** There should be currently 2 feedbacks left by End User, non of them are showing in Analytics module feedback to CSA chats "Tagasiside nõustajate vestlustele" and also in feedback to selected CSA "Tagasiside valitus nõustajale".

**Expected behavior:** It should show currently 2 feedbacks, that have been left by End User (28.10.2024).

**Screenshots:** 
![Image](https://github.com/user-attachments/assets/7e08e03a-9efd-46d2-9677-1aedabe52c9e)
![Image](https://github.com/user-attachments/assets/60a8d7f9-f8fb-4393-80c9-3e7a8e9d66b0)

**Additional information:**

**Comment by IgorKrupenja** [comment]
Related PRs:

- https://github.com/buerokratt/DataMapper/pull/97
- https://github.com/buerokratt/Analytics-Module/pull/346

**Comment by jaX10bt** [comment]
Works as intended
