### ISSUE TITLE
[BUG] Changing conversation status

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#946]
**Bug description:** When an CSA starts to change the “Conversation Status” and makes a selection but then decides to cancel and presses “Cancel” (instead of “Save”), the selected option remains in the “Conversation Status” field. Upon closing the conversation history overview by pressing the close button, it appears that the change was not saved as intended. However, this creates confusion as to whether the initially selected option was saved as the conversation status despite pressing “Cancel.” Could it be set to automatically default back to the original selection after pressing “Cancel”? (Initially, the field appears empty with “Select” as the default, even if a status was previously chosen.)

**Expected behavior:**

**Screenshots:**
![Image](https://github.com/user-attachments/assets/94d51487-8644-44c8-a0dc-8676249e12b5)

![Image](https://github.com/user-attachments/assets/43cd2e00-be86-4e92-aeeb-4a30dcd1daca)

![Image](https://github.com/user-attachments/assets/9f7d5b97-5dcb-4c13-b32a-98cdb9b3fdbe)

**Additional information:**

**Comment by ExiRain** [comment]
New change on open selects previously selected state
[Pull request](https://github.com/buerokratt/Buerokratt-Chatbot/pull/999).
