### ISSUE TITLE
Change notifycation for End User, that chat has been taken over by CSA

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#965]
**AS A** *End User*
**I WANT TO** *get notified when CSA takes over the chat*
**SO THAT I** *know whether I am chatting with a robot or with a human*

### Acceptance Criteria

- [x] When CSA takes over the chat, a notification CSA took over conversation "Klienditeenindaja võttis vestluse üle" is displayed in the widget, indicating that the end user is now chatting with a human. Currently it displays human took over conversation "Inimene võttis vestluse üle".

**Comment by ExiRain** [comment]
Updated texts:
Widget [PR](https://github.com/buerokratt/Chat-Widget/pull/335).
Chatbot [PR](https://github.com/buerokratt/Buerokratt-Chatbot/pull/1002).

**Comment by ffrose** [comment]
Works as intended.
