### ISSUE TITLE
Disable forwarding chats for himself

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#966]
**AS A** *CSA*
**I WANT** *to see only other CSA-s in chat forwarding list*
**SO THAT** *I can choose between other CSA-s and not see my name in the list*

### Acceptance Criteria

- [x] Forwarding list shows list of CSA-s and does not display person in the list, who is currently forwarding the chat.

**Comment by ffrose** [comment]
Works as intended.
