### ISSUE TITLE
Chat module chat window displays

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#967]
**AS A** *CSA*
**I WANT** *to see in chat module open chat Bürokratt/CSA answers in left side and End User replays in right side of the chat window*
**SO THAT** *I can see answers by CSA or End User more easily*

### Acceptance Criteria

- [ ] In (Chat module) open chat window CSA or Bürokratt answers are in left side and End User text is in right side (similar to widget).

**Comment by ExiRain** [comment]
Updated styling
Related [PR](https://github.com/buerokratt/Buerokratt-Chatbot/pull/1006)

**Comment by ffrose** [comment]
As of right now, Bürokratt, CSA and End-User messages are all on the left side.
![Image](https://github.com/user-attachments/assets/289473db-9d5e-48e5-b76d-082c1e5a264d)

End-User messages should be located on the right side.
