### ISSUE TITLE
[BUG] Chat history dropdown scrollable inside card

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#970]
**Bug description:**
In /chat/history the search card becomes scrollable when opening the dropdown. It seems to be due to the card style being `overflow-y: auto`

**Expected behavior:**
The dropdown opens on top of the lower card without the upper card becoming scrollable.

**Video:**
https://github.com/user-attachments/assets/bcaee51e-7f80-4241-b4a1-843940514c74

**Comment by ffrose** [comment]
Working as intended.
