### ISSUE TITLE
[BUG] Administrative module user search

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#974]
**Bug description:**
In administrative module user search, when clicking on user search magnifier, then pop-up box hides first row name. And when searching name, that is not in list, pop-up box disappears and comes back only when double clicking magnifier.

**Expected behavior:**
When searching user, pop-up box does not hide first row name and when user is not existing pop-up box stays visual.

**Screenshots:**
Pop-p box hides first row name:
![Image](https://github.com/user-attachments/assets/f1c79ace-9a29-4d23-92af-968bd9c62249)

Pop-up box hides when user is not in list:
![Image](https://github.com/user-attachments/assets/f5bcd028-4bea-4f12-9ee7-2f01ca8871d3)

**Additional information:**

**Comment by ffrose** [comment]
Working as intended.
