### ISSUE TITLE
Common service answers

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#982]
**AS A** *Chatbot trainer*
**I WANT** *common service data answer to be correct*
**SO THAT** *I can have correct answers from common service*

### Acceptance Criteria

- [x] Dates are in dd.mm.yyyy format
- [x] Consumer price index has correct year and if needed month added to the answer
- [x] Unemployment rate has correct year added to the answer
- [x] Persons related to the company answer is built up with only first capital letter (for example Osade registripidaja, Juhatuse liige, etc)
- [x] Companies revenue and taxes show year and quarter in the answer (for example "2024 aasta III kvartal" [2024 year III quarter])
- [x] Companies contacts answer is built up with only first capital letter (E-post, Telefon)
- [x] Answers are displayed as in Common_service excel table suggests

**Comment by matKlju** [comment]
Works as intended
